version: '3.9'

services:
  nginxSrv:
    image: nginx:1.25.2
    container_name: nginx
    volumes:
      - ./conf/nginx.conf:/etc/nginx/nginx.conf:ro
      - static-data:/static
      - ./conf/crt/device.key:/etc/nginx/ssl/device.key
      - ./conf/crt/mysite.localhost.crt:/etc/nginx/ssl/mysite.localhost
    command: [nginx-debug, '-g', 'daemon off;']
    ports:
      - "80:80"
      - 443:443

  djangoSrv:
    build: .
    image: djapp:latest
    container_name: djangoStage
#    command: python manage.py runserver 0.0.0.0:8000
#    command: gunicorn -c conf/gunicorn_config.py djangoProjectStage.wsgi
    volumes:
      - static-data:/app/static
#    ports:
#      - "8000:8000"

volumes:
  static-data: